### ISSUE TITLE
TinyDriverRos

### ISSUE THREAD

**Issue by Philippe117** [WalkingMachine/wm_lifting_column_arduino#3]
subscribe:
- /column/position std_msgs/Uint32
- /column/goal std_msgs/Float64

publish:
- /column/cmd std_msgs/Int8
- /column/state sensor_msgs/JointState

**Comment by JeffCousineau** [comment]
/column/goal ?

**Comment by Philippe117** [comment]
wep, la position à ateindre en m

**Comment by JeffCousineau** [comment]
Legit :P
